name: Testing using live NCAR records
on:
  schedule:
  # Run every day at 4 AM UTC
  - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      system:
        description: "Test System"
        required: true
        default: "both"
        type: choice
        options:
        - both
        - casper
        - derecho

jobs:
  casper-test:
    name: ⚗️  Test qhist parsing on live Casper data
    runs-on: casper-runner
    if: github.event_name == 'schedule' || contains(fromJSON('["both","casper"]'), inputs.system)

    steps:
    - name: Ensure clean working directory
      run: ls -la $GITHUB_WORKSPACE
      #run: rm -rf $GITHUB_WORKSPACE
    - uses: actions/checkout@v4
    - name: Install qhist with Makefile
      run: make install PREFIX=install
    - name: Test qhist and check status
      run: |
        bin/qhist > /dev/null
      working-directory: install
  
  derecho-test:
    name: ⚗️  Test qhist parsing on live Derecho data
    runs-on: derecho-runner
    if: github.event_name == 'schedule' || contains(fromJSON('["both","derecho"]'), inputs.system)

    steps:
      #- name: Ensure clean working directory
      #  run: rm -rf $GITHUB_WORKSPACE
    - uses: actions/checkout@v4
    - name: Install qhist with Makefile
      run: make install PREFIX=install
    - name: Test qhist and check status
      run: |
        bin/qhist > /dev/null
      working-directory: install
